files: []

units:
  - path: /autoware/modes/local
    type: and
    list:
      - { type: link, link: /autoware/system/rosbag/node_alive }

  - path: /autoware/modes/remote
    type: and
    list:
      - { type: link, link: /autoware/system/rosbag/node_alive }

  - path: /autoware/modes/stop
    type: and
    list:
      - { type: link, link: /autoware/system/rosbag/node_alive }

  - path: /autoware/modes/autonomous
    type: and
    list:
      - { type: link, link: /autoware/system/rosbag/node_alive }

  - path: /autoware/modes/pull_over
    type: and
    list:
      - { type: link, link: /autoware/system/rosbag/node_alive }

  - path: /autoware/modes/comfortable_stop
    type: and
    list:
      - { type: link, link: /autoware/system/rosbag/node_alive }

  - path: /autoware/modes/emergency_stop
    type: and
    list:
      - { type: link, link: /autoware/system/rosbag/node_alive }

  - path: /autoware/system/rosbag/node_alive
    type: diag
    node: rosbag_node_monitor
    name: rosbag_node_alive
    timeout: 2.0
